version: '3.8'

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    env_file:
      - ./mysql/.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api/app
        target: /go/src
    platform: linux/amd64

  db:
    container_name: db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    tty: true
    env_file:
      - ./mysql/.env
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_database
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initsql:/docker-entrypoint-initdb.d
    platform: linux/x86_64

  # フロントエンドのコンテナ
  spa:
    build: ./spa/reactapp
    container_name: spa
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./spa/reactapp:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - '3000:3000'
    platform: linux/x86_64

volumes:
  db-store-life:
