version: '3.7'

services:
  # appコンテナ
  app:
    build:
      context: .
      dockerfile: build/app/Dockerfile
    container_name: life-sim-go-app
    depends_on:
      - db
    env_file:
      - .env
      - .env.docker
    expose:
      # nginxから転送されたリクエストを受信
      - '8080'
    image: life-sim-go-app:latest
    hostname: app
    networks:
      - default
    tty: true
    volumes:
      - .:/go/src

  # webコンテナ
  web:
    build:
      context: .
      dockerfile: build/web/Dockerfile
      target: develop
    container_name: life-sim-go-web
    depends_on:
      - app
    image: life-sim-go-web:latest
    hostname: web
    ports:
      - '8001:80'
    networks:
      - default

  # dbコンテナ
  db:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: life-sim-go-db
    env_file:
      # NOTE: docker-compose.ymlで使用する変数を展開するために読み込む．
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'
    image: mysql:5.7
    hostname: db
    ports:
      - '3306:3306'
    networks:
      - default
    volumes:
      - db_volume:/var/lib/mysql
    platform: linux/x86_64

volumes:
  db_volume:
    driver: local

networks:
  default:
    name: life-sim-go-gin
