version: "3.7"

services:

  # appコンテナ
  app:
    build:
      context: .
      dockerfile: build/app/Dockerfile
    container_name: ddd-backend-with-gin-app
    depends_on:
      - db
    env_file:
      - .env
      - .env.docker
    expose:
      # nginxから転送されたリクエストを受信
      - "8080"
    image: ddd-backend-with-gin-app:latest
    hostname: app
    networks:
      - default
    tty: true
    volumes:
      - .:/go/src

  # webコンテナ
  web:
    build:
      context: .
      dockerfile: build/web/Dockerfile
      target: develop
    container_name: ddd-backend-with-gin-web
    depends_on:
      - app
    image: ddd-backend-with-gin-web:latest
    hostname: web
    ports:
      - "8001:80"
    networks:
      - default

  # dbコンテナ
  db:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    container_name: ddd-backend-with-gin-db
    env_file:
      # NOTE: docker-compose.ymlで使用する変数を展開するために読み込む．
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
    image: mysql:5.7
    hostname: db
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - db_volume:/var/lib/mysql

volumes:
  db_volume:
    driver: local

networks:
  default:
    name: ddd-backend-with-gin
